/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StoryData = IDL.Record({
  'xHandle' : IDL.Text,
  'story' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'xHandle' : IDL.Text,
});
export const StorySubmission = IDL.Record({
  'xHandle' : IDL.Text,
  'story' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteStory' : IDL.Func([IDL.Nat], [], []),
  'findStoriesByXHandle' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StoryData)],
      ['query'],
    ),
  'getAllStories' : IDL.Func([], [IDL.Vec(StoryData)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitStory' : IDL.Func([StorySubmission], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StoryData = IDL.Record({
    'xHandle' : IDL.Text,
    'story' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'xHandle' : IDL.Text });
  const StorySubmission = IDL.Record({
    'xHandle' : IDL.Text,
    'story' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteStory' : IDL.Func([IDL.Nat], [], []),
    'findStoriesByXHandle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StoryData)],
        ['query'],
      ),
    'getAllStories' : IDL.Func([], [IDL.Vec(StoryData)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitStory' : IDL.Func([StorySubmission], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };